//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pixy
{
    sealed class pixy
    {
        public static int pixy_init()
        {
            int ret = pixyPINVOKE.pixy_init();
            return ret;
        }

        public static int pixy_get_blocks(ushort max_blocks, BlockArray blocks)
        {
            int ret = pixyPINVOKE.pixy_get_blocks(max_blocks, BlockArray.getCPtr(blocks));
            return ret;
        }

        public static void pixy_close()
        {
            pixyPINVOKE.pixy_close();
        }

        public static int pixy_blocks_are_new()
        {
            int ret = pixyPINVOKE.pixy_blocks_are_new();
            return ret;
        }

        public static int pixy_cam_set_auto_white_balance(byte value)
        {
            int ret = pixyPINVOKE.pixy_cam_set_auto_white_balance(value);
            return ret;
        }

        public static int pixy_cam_get_auto_white_balance()
        {
            int ret = pixyPINVOKE.pixy_cam_get_auto_white_balance();
            return ret;
        }

        public static uint pixy_cam_get_white_balance_value()
        {
            uint ret = pixyPINVOKE.pixy_cam_get_white_balance_value();
            return ret;
        }

        public static int pixy_cam_set_white_balance_value(byte red, byte green, byte blue)
        {
            int ret = pixyPINVOKE.pixy_cam_set_white_balance_value(red, green, blue);
            return ret;
        }

        public static int pixy_cam_set_auto_exposure_compensation(byte enable)
        {
            int ret = pixyPINVOKE.pixy_cam_set_auto_exposure_compensation(enable);
            return ret;
        }

        public static int pixy_cam_get_auto_exposure_compensation()
        {
            int ret = pixyPINVOKE.pixy_cam_get_auto_exposure_compensation();
            return ret;
        }

        public static int pixy_cam_set_exposure_compensation(byte gain, ushort compensation)
        {
            int ret = pixyPINVOKE.pixy_cam_set_exposure_compensation(gain, compensation);
            return ret;
        }

        public static int pixy_cam_get_exposure_compensation(out byte gain, out ushort compensation)
        {
            int ret = pixyPINVOKE.pixy_cam_get_exposure_compensation(out gain, out compensation);
            return ret;
        }

        public static int pixy_cam_set_brightness(byte brightness)
        {
            int ret = pixyPINVOKE.pixy_cam_set_brightness(brightness);
            return ret;
        }

        public static int pixy_cam_get_brightness()
        {
            int ret = pixyPINVOKE.pixy_cam_get_brightness();
            return ret;
        }

        public static readonly int PIXY_MIN_X = pixyPINVOKE.PIXY_MIN_X_get();
        public static readonly int PIXY_MAX_X = pixyPINVOKE.PIXY_MAX_X_get();
        public static readonly int PIXY_MIN_Y = pixyPINVOKE.PIXY_MIN_Y_get();
        public static readonly int PIXY_MAX_Y = pixyPINVOKE.PIXY_MAX_Y_get();
    }

}